export const formTypes = {
    FETCH_FAVORITE: "FETCH_FAVORITE",
    FETCH_FAVORITE_START: "FETCH_FAVORITE_START",
    FETCH_FAVORITE_SUCCESS: "FETCH_FAVORITE_SUCCESS",
    FETCH_FAVORITE_FAIL: "FETCH_FAVORITE_FAIL",
    ADD_FAVORITE: "ADD_FAVORITE",
    REMOVE_FAVORITE: "REMOVE_FAVORITE",


    SET_STEP: "SET_STEP",
    SET_STEP_UP: "SET_STEP_UP",
    SET_STEP_DOWN: "SET_STEP_DOWN",
    SET_VENDOR: "SET_VENDOR",
    SET_TYPE: "SET_TYPE",
    SET_REV_RANGE: "SET_REV_RANGE",
    SET_INDUSTRY: "SET_INDUSTRY",
    SET_AVERAGE_COMMISION: "SET_AVERAGE_COMMISION",
    SET_OPTION: "SET_OPTION",
    SET_CURRENT_COMPANY: "SET_CURRENT_COMPANY",

    CLOSE_RESULTS: "CLOSE_RESULTS",
    TOGGLE_MAIL_FORM: "TOGGLE_MAIL_FORM",
    MAIL_SENT: "MAIL_SENT",
}